:experimental:
:imagesdir: ./images
= soapui-reprezen-plugin

The SoapUI RepreZen plugin allows SmartBear's open source http://www.soapui.org/[SoapUI] and commercial http://smartbear.com/product/ready-api/overview/[Ready! API] tools to work with API models created by http://www.reprezen.com[RepreZen API Studio].  With the SoapUI RepreZen plugin, you can:

* Import RepreZen's native http://rapid-api.org/rapid-ml[RAPID-ML] API models into SoapUI or Ready! API for testing and virtualization.
* Generate an API model in RAPID-ML format from any REST API defined in SoapUI or Ready! API, for subsequent editing, documentation, visualization and code generation in RepreZen API Studio.

== Download & Install

To install the plugin to Ready! API:

. Download the plugin JAR file from the https://github.com/RepreZen/soapui-reprezen-plugin/tree/master/jars[jars page], or <<building-the-plugin,build it yourself>> as described below.

. In Ready! API, click the btn:[Plugins] toolbar button to show the Plugin Manager.

. Click the btn:[Load plugin from file...] button, and open the plugin JAR file. You should see a message box indicating that the plugin has been installed successfully.  Click btn:[OK], then btn:[Close] to dismiss the Plugin Manager.

The RepreZen SoapUI plugin is now ready to import and export RepreZen API Studio's native http://rapid-apij.org/rapid-ml[RAPID-ML] format.

NOTE: The export action is available on the _RestResource_, not on the project itself.  See <<working-with-the-plugin,Working with the Plugin>> below for more details.

== Building the Plugin

To build the RepreZen SoapUI Plugin, clone the Git repository, make sure you have maven installed, and run

```
mvn clean install assembly:single
```
NOTE: Maven creates two jars.  We recommend using `soapui-reprezen-plugin/target/soapui-reprezen-plugin-1.0-dist.jar` as it contains all of the required dependencies.

== Working with the Plugin
=== Importing a RAPID-ML API Models
RepreZen API Studio's _Zen Model_ or _RAPID Model_ is an API description in RAPID-ML format.
=== Exporting a REST API to RepreZen API Studio
RAPID-ML Models for use in RepreZen
